### ISSUE TITLE
cannot import name 'Blueprint' from 'android_bp'

### ISSUE THREAD

**Issue by kdhj** [tardyp/rs-bp#2]
Exception has occurred: ImportError
cannot import name 'Blueprint' from 'android_bp' (/home/tublack/.local/lib/python3.10/site-packages/android_bp/__init__.py)
  File "/home/tublack/Android/packages/modules/Bluetooth/java_dep.py", line 4, in <module>
    from android_bp import Blueprint
ImportError: cannot import name 'Blueprint' from 'android_bp' (/home/tublack/.local/lib/python3.10/site-packages/android_bp/__init__.py)
![image](https://github.com/user-attachments/assets/d5bff5a3-592c-4362-9a08-267f99816c1e)

**Comment by nigangkaka** [comment]
Please use 

from android_bp import BluePrint

instead of 
from android_bp import Blueprint

**Comment by tardyp** [comment]
the readme is now fixed. thanks
